server:
  port: 8081
spring:
  application:
    name: library-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  http://auth-server:9090/oauth2/jwks #http://localhost:9090/oauth2/jwks





