spring:
  application:
    name: auth-service
  security:
    user:
      name: admin
      password: admin
server:
  port: 9090
logging:
  level:
    org:
      springframework:
        security: TRACE
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}